version: "3.3"
services:
  db:
    image: postgres:10
    container_name: example_postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pgquery_example
    volumes:
      - pg_conf:/etc/postgresql
      - pg_log:/var/log/postgresql
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
  pg_conf:
  pg_log: