language: scala
scala:
  - 2.13.5

dist: bionic

script:
  - cd parser/src/main/native/libpg_query
  - make
  - cd ../../../../..
  - sbt parser/compileWrapper
  - sbt parser/test
  - sbt example/run
