language: scala
scala:
  - 2.13.5

dist: bionic

script:
  - cd native/src/native/libpg_query
  - make
  - cd ../../../..
  - sbt test publishLocal
  - cd example
  - docker-compose -f docker-compose.yml up -d
  - sbt run
