language: scala
scala:
  - 2.13.5

dist: bionic

script:
  - cd parser/src/main/native/libpg_query
  - make
  - cd ../../../../..
  - sbt parser/compileWrapper
  - sbt parser/test
  - sbt publishLocal
  - cd example
  - docker-compose -f docker-compose.yml up -d
  - sbt run