language: scala
scala:
  - 2.13.5

dist: xenial
sudo: required

services:
  - postgresql

before_script:
  - psql -c 'create database pgquery_example;' -U postgres

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

env:
  global:
    - PGUSER=postgres
    - PGPORT=5432

script:
  - cd native/src/native/libpg_query
  - make
  - cd ../../../..
  - sbt test publishLocal
  - cd example
  - sbt run
