language: scala
scala:
  - 2.13.5

dist: bionic

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_script:
  - psql -c 'create database pgquery_example'; -U postgres

script:
  - cd native/src/native/libpg_query
  - make
  - cd ../../../..
  - sbt test publishLocal
  - cd example
  - sbt run
