language: scala
scala:
  - 2.13.5

dist: xenial
sudo: required

services:
  - postgresql

before_script:
  - psql -c 'create database pgquery_example;' -U postgres

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-10 postgresql-client-10
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo service postgresql restart 10

env:
  global:
    - PGUSER=postgres
    - PGPORT=5432

script:
  - cd native/src/native/libpg_query
  - make
  - cd ../../../..
  - sbt test publishLocal
  - cd example
  - sbt run
