version: "3.3"
services:
  db:
    image: postgres:10
    ports:
      - "5439:5439"
    environment:
      -  POSTGRES_PASSWORD=password
    volumes:
      - pg_conf:/etc/postgresql
      - pg_log:/var/log/postgresql
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
  pg_conf:
  pg_log: