/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_ivellien_pgquery_core_PgQueryWrapper */

#ifndef _Included_com_github_ivellien_pgquery_parser_PgQueryWrapper
#define _Included_com_github_ivellien_pgquery_parser_PgQueryWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_ivellien_pgquery_parser_PgQueryWrapper
 * Method:    pgQueryParse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_ivellien_pgquery_parser_PgQueryWrapper_pgQueryParse
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
