/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PgQueryWrapper */

#ifndef _Included_PgQueryWrapper
#define _Included_PgQueryWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PgQueryWrapper
 * Method:    pgQueryParse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_PgQueryWrapper_pgQueryParse
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
